### ISSUE TITLE
Time picker UI component

### ISSUE THREAD

**Issue by Abhinavcode13** [thekavikumar/love-simple-ui#115] opened 2023-06-02 18:16 UTC
### Current Behavior
To add a UI component not present yet.

### Desired Behavior
Time Picker: Allows users to select a time from a clock-like interface.

### Screenshots / Mockups

![image](https://github.com/thekavikumar/love-simple-ui/assets/126642111/57fb1025-4800-4725-bf19-4303c1265c9a)

---

**Comment by Abhinavcode13** [comment] 2023-06-02 18:16
Please assign me this issue @thekavikumar 

thankyou

**Comment by Abhinavcode13** [comment] 2023-06-05 15:41
The issue is already resolved and merged @MukulsinghRajpurohit

**Comment by MukulsinghRajpurohit** [comment] 2023-06-05 17:06
@Abhinavcode13 if this has been merge then why not it has been add in src folder and you are saying that The issue is already resolved and merged please provide code source link

**Comment by Abhinavcode13** [comment] 2023-06-05 17:08
![image](https://github.com/thekavikumar/love-simple-ui/assets/126642111/a8302791-1a04-4a58-b065-2b0af94b2a3a)
Hope this clear it @MukulsinghRajpurohit

**Closed** 2024-12-29 17:58 UTC
Labels: GSSoC
